// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb82tU7khNrWhUyQxYWsNtfQOnLqUpJgQ',
    appId: '1:975427578934:web:71a94100c47f1d2fc5bc97',
    messagingSenderId: '975427578934',
    projectId: 'rapidresq-33688',
    authDomain: 'rapidresq-33688.firebaseapp.com',
    storageBucket: 'rapidresq-33688.firebasestorage.app',
    measurementId: 'G-D0H930QN24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3IxvzzBWmphEEq2OMQ0q6grOssS5Cag',
    appId: '1:975427578934:android:10fbd7ca864b90bac5bc97',
    messagingSenderId: '975427578934',
    projectId: 'rapidresq-33688',
    storageBucket: 'rapidresq-33688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1ztZwfYWDTbt7giy6rBrBn5mywHOAck',
    appId: '1:975427578934:ios:5f7a7a2c10073c06c5bc97',
    messagingSenderId: '975427578934',
    projectId: 'rapidresq-33688',
    storageBucket: 'rapidresq-33688.firebasestorage.app',
    iosBundleId: 'com.example.rapidresq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1ztZwfYWDTbt7giy6rBrBn5mywHOAck',
    appId: '1:975427578934:ios:5f7a7a2c10073c06c5bc97',
    messagingSenderId: '975427578934',
    projectId: 'rapidresq-33688',
    storageBucket: 'rapidresq-33688.firebasestorage.app',
    iosBundleId: 'com.example.rapidresq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb82tU7khNrWhUyQxYWsNtfQOnLqUpJgQ',
    appId: '1:975427578934:web:f507fe5621a22d29c5bc97',
    messagingSenderId: '975427578934',
    projectId: 'rapidresq-33688',
    authDomain: 'rapidresq-33688.firebaseapp.com',
    storageBucket: 'rapidresq-33688.firebasestorage.app',
    measurementId: 'G-N88CE3S4CS',
  );
}
